using System;

namespace Close_Portal.Services {

    // Todas las cadenas traducibles de los correos de alerta.
    // C# inline — sin archivos de recursos, sin magic keys.
    public static class EmailStrings {

        // ── Footer ────────────────────────────────────────────────────────────
        public static string FooterAuto(string lang) => lang == "en"
            ? "Automatic notification generated by Close Portal."
            : "Notificación automática generada por Close Portal.";

        public static string FooterNoReply(string lang) => lang == "en"
            ? "This is an informational email, please do not reply to this address."
            : "Este es un correo informativo, por favor no respondas a esta dirección.";

        // ── Etiquetas comunes ─────────────────────────────────────────────────
        public static string LDate(string lang)          => lang == "en" ? "Date"                     : "Fecha";
        public static string LBy(string lang)            => lang == "en" ? "Performed by"             : "Realizado por";
        public static string LActionBy(string lang)      => lang == "en" ? "Action performed by"      : "Acción realizada por";
        public static string LUser(string lang)          => lang == "en" ? "User"                     : "Usuario";
        public static string LRole(string lang)          => lang == "en" ? "Assigned role"            : "Rol asignado";
        public static string LNewRole(string lang)       => lang == "en" ? "New role"                 : "Nuevo rol";
        public static string LWarehouse(string lang)     => lang == "en" ? "Warehouse"                : "Bodega";
        public static string LRequestedBy(string lang)   => lang == "en" ? "Requested by"             : "Solicitado por";
        public static string LStart(string lang)         => lang == "en" ? "Start"                    : "Inicio";
        public static string LScheduledStart(string lang)=> lang == "en" ? "Scheduled start"          : "Inicio programado";
        public static string LPrevStart(string lang)     => lang == "en" ? "Previously scheduled start": "Inicio que estaba programado";
        public static string LConfirmedBy(string lang)   => lang == "en" ? "Confirmed by"             : "Confirmada por";
        public static string LCancelledBy(string lang)   => lang == "en" ? "Cancelled by"             : "Cancelada por";
        public static string LCreatedBy(string lang)     => lang == "en" ? "Created by"               : "Creada por";
        public static string LTriggeredBy(string lang)   => lang == "en" ? "Triggered by"             : "Disparado por";
        public static string LLocation(string lang)      => lang == "en" ? "Location"                 : "Locación";
        public static string LStatus(string lang)        => lang == "en" ? "Status"                   : "Estado";
        public static string LReviewedBy(string lang)    => lang == "en" ? "Reviewed by"              : "Revisado por";
        public static string LReviewerComment(string lang)=> lang == "en" ? "Reviewer's comment"      : "Comentario del revisor";
        public static string LNotifDate(string lang)     => lang == "en" ? "Notification date"        : "Fecha de notificación";
        public static string LScheduledOn(string lang)   => lang == "en" ? "Scheduled on"             : "Programada el";
        public static string LClosureDate(string lang)   => lang == "en" ? "Closure recorded"         : "Cierre registrado";
        public static string LReminderDate(string lang)  => lang == "en" ? "This reminder's date"     : "Fecha de este recordatorio";
        public static string LRequest(string lang)       => lang == "en" ? "Request"                  : "Solicitud";
        public static string LChanges(string lang)       => lang == "en" ? "Changes made"              : "Cambios realizados";
        public static string LApproved(string lang)      => lang == "en" ? "Approved ✓"               : "Aprobada ✓";
        public static string LRejected(string lang)      => lang == "en" ? "Rejected ✗"               : "Rechazada ✗";
        public static string NoName(string lang)         => lang == "en" ? "(no name)"                : "(sin nombre)";
        public static string System_(string lang)        => lang == "en" ? "System"                   : "Sistema";
        public static string Unassigned(string lang)     => lang == "en" ? "Unassigned"               : "Sin asignar";

        // ── UserAdded ─────────────────────────────────────────────────────────
        public static string UserAdded_Subject(string lang, string name) => lang == "en"
            ? $"User added: {name}" : $"Usuario agregado: {name}";
        public static string UserAdded_Title(string lang) => lang == "en"
            ? "New user added" : "Nuevo usuario agregado";

        // ── UserRemoved ───────────────────────────────────────────────────────
        public static string UserRemoved_Subject(string lang, string name) => lang == "en"
            ? $"User deactivated: {name}" : $"Usuario desactivado: {name}";
        public static string UserRemoved_Title(string lang) => lang == "en"
            ? "User deactivated" : "Usuario desactivado";

        // ── UserUpdated ───────────────────────────────────────────────────────
        public static string UserUpdated_Subject(string lang, string name) => lang == "en"
            ? $"User updated: {name}" : $"Usuario modificado: {name}";
        public static string UserUpdated_Title(string lang) => lang == "en"
            ? "User updated" : "Usuario modificado";

        // ── ClosureRequest ────────────────────────────────────────────────────
        public static string ClosureRequest_Subject(string lang, string wmsCode) => lang == "en"
            ? $"Closure request — {wmsCode}" : $"Solicitud de cierre — {wmsCode}";
        public static string ClosureRequest_Title(string lang) => lang == "en"
            ? "Closure request" : "Solicitud de cierre";
        public static string ClosureRequest_Intro(string lang, string managerName) => lang == "en"
            ? $"Hello <strong>{managerName}</strong>, you have a new pending closure request."
            : $"Hola <strong>{managerName}</strong>, tienes una nueva solicitud de cierre pendiente.";
        public static string ClosureRequest_Footer(string lang, int requestId) => lang == "en"
            ? $"Request #{requestId} — Close Portal." : $"Solicitud #{requestId} — Close Portal.";

        // ── GuardStarted ──────────────────────────────────────────────────────
        public static string GuardStarted_Subject(string lang, DateTime t) => lang == "en"
            ? $"Guard started — {t:dd/MM/yyyy HH:mm} hrs" : $"Guardia iniciada — {t:dd/MM/yyyy HH:mm} hrs";
        public static string GuardStarted_Title(string lang) => lang == "en"
            ? "Guard started" : "Guardia iniciada";
        public static string GuardStarted_Intro(string lang, DateTime t, string by) => lang == "en"
            ? $"Guard started on <strong>{t:dd/MM/yyyy}</strong> at <strong>{t:HH:mm} hrs</strong> by <strong>{by}</strong>."
            : $"Guardia iniciada el <strong>{t:dd/MM/yyyy}</strong> a las <strong>{t:HH:mm} hrs</strong> por <strong>{by}</strong>.";

        // ── GuardClosed ───────────────────────────────────────────────────────
        public static string GuardClosed_Subject(string lang, DateTime t) => lang == "en"
            ? $"Guard closed — {t:dd/MM/yyyy HH:mm} hrs" : $"Guardia cerrada — {t:dd/MM/yyyy HH:mm} hrs";
        public static string GuardClosed_Title(string lang) => lang == "en"
            ? "Guard closed" : "Guardia cerrada";
        public static string GuardClosed_Line1(string lang) => lang == "en"
            ? "<b>All locations closed successfully.</b>" : "<b>Todas las locaciones cerraron correctamente.</b>";

        // ── GuardDraft ────────────────────────────────────────────────────────
        public static string GuardDraft_Subject(string lang, DateTime t) => lang == "en"
            ? $"Guard scheduled — {t:dd/MM/yyyy HH:mm} hrs" : $"Guardia programada — {t:dd/MM/yyyy HH:mm} hrs";
        public static string GuardDraft_Title(string lang) => lang == "en"
            ? "Guard scheduled" : "Guardia programada";
        public static string GuardDraft_Line1(string lang) => lang == "en"
            ? "<b>A new closing guard has been scheduled.</b>" : "<b>Se ha programado una nueva guardia de cierre.</b>";
        public static string GuardDraft_Note(string lang) => lang == "en"
            ? "<span style='color:#64748b;font-size:13px;'>The guard is in draft state. It can still be cancelled or modified.</span>"
            : "<span style='color:#64748b;font-size:13px;'>La guardia se encuentra en estado borrador. Aún puede cancelarse o modificarse.</span>";

        // ── GuardDraftCancelled ───────────────────────────────────────────────
        public static string GuardDraftCancelled_Subject(string lang, string fecha) => lang == "en"
            ? $"Guard cancelled (draft) — {fecha}" : $"Guardia cancelada (draft) — {fecha}";
        public static string GuardDraftCancelled_Title(string lang) => lang == "en"
            ? "Draft guard cancelled" : "Guardia draft cancelada";
        public static string GuardDraftCancelled_Line1(string lang) => lang == "en"
            ? "<b>The scheduled draft guard has been cancelled.</b>" : "<b>La guardia programada en borrador ha sido cancelada.</b>";

        // ── GuardConfirmed ────────────────────────────────────────────────────
        public static string GuardConfirmed_Subject(string lang, string fecha) => lang == "en"
            ? $"Guard confirmed — {fecha}" : $"Guardia confirmada — {fecha}";
        public static string GuardConfirmed_Title(string lang) => lang == "en"
            ? "Guard confirmed" : "Guardia confirmada";
        public static string GuardConfirmed_Intro(string lang) => lang == "en"
            ? "The guard has been <strong>confirmed and is active</strong>."
            : "La guardia ha sido <strong>confirmada y está activa</strong>.";

        // ── GuardCancelled ────────────────────────────────────────────────────
        public static string GuardCancelled_Subject(string lang, string fecha) => lang == "en"
            ? $"Guard cancelled — {fecha}" : $"Guardia cancelada — {fecha}";
        public static string GuardCancelled_Title(string lang) => lang == "en"
            ? "Guard cancelled" : "Guardia cancelada";
        public static string GuardCancelled_Line1(string lang) => lang == "en"
            ? "<b>The active guard has been cancelled.</b>" : "<b>La guardia activa ha sido cancelada.</b>";

        // ── ClosureResponse ───────────────────────────────────────────────────
        public static string ClosureResponse_StatusLabel(string lang, bool approved) {
            if (lang == "en") return approved ? "approved" : "rejected";
            return approved ? "aprobada" : "rechazada";
        }
        public static string ClosureResponse_Subject(string lang, string label, string location) => lang == "en"
            ? $"Closure request {label} — {location}" : $"Solicitud de cierre {label} — {location}";
        public static string ClosureResponse_Title(string lang, string label) => lang == "en"
            ? $"Request {label}" : $"Solicitud {label}";
        public static string ClosureResponse_Line1(string lang, string name, string label) => lang == "en"
            ? $"Hello <b>{name}</b>, your closure request was <b>{label}</b>."
            : $"Hola <b>{name}</b>, tu solicitud de cierre fue <b>{label}</b>.";

        // ── UserBlocked ───────────────────────────────────────────────────────
        public static string UserBlocked_Subject(string lang) => lang == "en"
            ? "Your account has been blocked" : "Tu cuenta ha sido bloqueada";
        public static string UserBlocked_Title(string lang) => lang == "en"
            ? "Account blocked" : "Cuenta bloqueada";
        public static string UserBlocked_Line1(string lang, string name) => lang == "en"
            ? $"Hello <b>{name}</b>." : $"Hola <b>{name}</b>.";
        public static string UserBlocked_Line2(string lang) => lang == "en"
            ? "Your <b>Close Portal</b> account has been temporarily blocked."
            : "Tu cuenta de <b>Close Portal</b> ha sido bloqueada temporalmente.";
        public static string UserBlocked_Line3(string lang) => lang == "en"
            ? "If you think this is an error, contact the system administrator."
            : "Si crees que esto es un error, contacta al administrador del sistema.";

        // ── UserUnblocked ─────────────────────────────────────────────────────
        public static string UserUnblocked_Subject(string lang) => lang == "en"
            ? "Your account has been unblocked" : "Tu cuenta ha sido desbloqueada";
        public static string UserUnblocked_Title(string lang) => lang == "en"
            ? "Account unblocked" : "Cuenta desbloqueada";
        public static string UserUnblocked_Line2(string lang) => lang == "en"
            ? "Your <b>Close Portal</b> account has been unblocked. You can now log in."
            : "Tu cuenta de <b>Close Portal</b> ha sido desbloqueada. Ya puedes iniciar sesión.";

        // ── DefaultSpotReminder ───────────────────────────────────────────────
        public static string DefaultSpotReminder_Subject(string lang, string dept) => lang == "en"
            ? $"Department {dept} unassigned — Active guard" : $"Departamento {dept} sin asignar — Guardia activa";
        public static string DefaultSpotReminder_Title(string lang, string dept) => lang == "en"
            ? $"Department {dept} unassigned" : $"Departamento {dept} sin responsable";
        public static string DefaultSpotReminder_Line1(string lang, string dept) => lang == "en"
            ? $"The guard has been confirmed but department <b>{dept}</b> has no assigned responsible."
            : $"La guardia ha sido confirmada pero el departamento de <b>{dept}</b> no tiene responsable asignado.";
        public static string DefaultSpotReminder_Line2(string lang) => lang == "en"
            ? "Please access Close Portal and assign a responsible for this department."
            : "Por favor, accede a Close Portal y asigna un responsable para este departamento.";

        // ── LocationReverted ──────────────────────────────────────────────────
        public static string LocationReverted_Subject(string lang, string locationName) => lang == "en"
            ? $"Location reverted — {locationName}" : $"Locación revertida — {locationName}";
        public static string LocationReverted_Title(string lang) => lang == "en"
            ? "Location reverted to active" : "Locación revertida a operación";
        public static string LocationReverted_Line1(string lang, string locationName) => lang == "en"
            ? $"The approved closure for location <b>{locationName}</b> has been reverted."
            : $"El cierre aprobado de la locación <b>{locationName}</b> ha sido revertido.";
        public static string LocationReverted_Line2(string lang) => lang == "en"
            ? "The location is now active again and may require a new closure request."
            : "La locación está nuevamente en operación y puede requerir una nueva solicitud de cierre.";

        // ── GuardDraftReminder ────────────────────────────────────────────────
        public static string GuardDraftReminder_Subject(string lang, int hours) => lang == "en"
            ? $"Reminder: unconfirmed guard ({hours}h)" : $"Recordatorio: guardia sin confirmar ({hours}h)";
        public static string GuardDraftReminder_Title(string lang) => lang == "en"
            ? "Unconfirmed guard" : "Guardia sin confirmar";
        public static string GuardDraftReminder_Line1(string lang, int hours, string plural) => lang == "en"
            ? $"There is a draft guard that has been unconfirmed for <b>{hours} hour{plural}</b>."
            : $"Existe una guardia en borrador que lleva <b>{hours} hora{plural}</b> sin ser confirmada.";
        public static string GuardDraftReminder_Line3(string lang) => lang == "en"
            ? "Please log into Close Portal and confirm or cancel the guard if it is no longer needed."
            : "Por favor, ingresa a Close Portal y confirma la guardia o cancélala si ya no es necesaria.";
    }
}
